# Generated by Django 4.1.3 on 2022-12-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codEquipo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('velocidadCPU', models.CharField(max_length=20)),
                ('fechaExpiracion', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=10))
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=20)),
                ('equipo', models.CharField(max_length=20)),
                ('fechaAsignacion', models.CharField(max_length=20)),
                
            ],
        ),
    ]
