# Generated by Django 3.1 on 2022-12-21 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('codEquipo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('velocidadCPU', models.CharField(max_length=20)),
                ('fechaExpiracion', models.DateField(verbose_name='Fecha de expiracion')),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=20)),
                ('fechaAsignacion', models.CharField(max_length=20)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pagina.equipos')),
            ],
        ),
    ]
