# Generated by Django 3.1 on 2022-12-14 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=20)),
                ('fechaAsignacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
        migrations.AlterField(
            model_name='equipos',
            name='fechaExpiracion',
            field=models.DateField(verbose_name='Fecha de expiracion'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.equipos'),
        ),
    ]
