# Generated by Django 3.1 on 2022-12-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadores',
            name='fechaAsignacion',
            field=models.DateField(verbose_name='Fecha de asignacion'),
        ),
    ]
