# Generated by Django 4.1.3 on 2022-12-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trabajador',
            new_name='Trabajadores',
        ),
    ]
