# Generated by Django 3.1 on 2022-12-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_auto_20221213_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='fechaExpiracion',
            field=models.DateField(blank=True, verbose_name='Fecha de expiracion'),
        ),
    ]
