# Generated by Django 3.1 on 2022-12-13 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_auto_20221212_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadores',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.equipos'),
        ),
    ]
