# Generated by Django 3.1 on 2022-12-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_auto_20221213_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='fechaExpiracion',
            field=models.DateField(null=True, verbose_name='Fecha de expiracion'),
        ),
    ]
