# Generated by Django 3.1 on 2022-12-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_auto_20221213_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='fechaExpiracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de expiracion'),
        ),
    ]
