# Generated by Django 3.1 on 2022-12-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_auto_20221212_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='fechaExpiracion',
            field=models.DateField(),
        ),
    ]
