# Generated by Django 3.1 on 2022-12-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_auto_20221212_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='fechaExpiracion',
            field=models.DateField(verbose_name='Fecha de expiracion'),
        ),
    ]
